name: deploy

# Controls when the workflow will run
on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: build wheel
        run: make wheel

      # This action performs the uploading of the artifact to Github
      - uses: actions/upload-artifact@v3
        with:
          name: pkg_wheel
          path: dist/*.tar.gz
