name: Simple workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push at feature branches
  push:
    branches: [ "feature/*" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  simple-job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: simple step
        run: echo "Hello Github Actions!"
      - name: use secret
        run: echo ${{ secrets.MY_NAME }}

